module Properties exposing (PropertyWidget(..), Button(..), PickerWidget(..), PropertyPalletState, toCommonProperties)

--This module contains data types used in the Property Pallet

import Color.Convert as CC
import Graphic
import Color exposing (Color)


type PropertyWidget
    = FillColor PickerWidget
    | StrokeColor PickerWidget
    | StrokeWidth Button



--PositionToColor is a function generated by the view code which takes a mouse position and produces a color
--This needs to be generated by the view code because that determines the positioning of the color picker elements


type PickerWidget
    = SaturationLightness PositionToColor
    | Hue PositionToColor
    | Background
    | ColorBox


type Button
    = Increment
    | Decrement


type alias PositionToColor =
    { x : Int, y : Int } -> Color


type alias PropertyPalletState =
    { fillColor : Color
    , strokeColor : Color
    , strokeWidth : Float

    --, colorPickerState : ColorPickerState
    }


toCommonProperties : PropertyPalletState -> Graphic.CommonAttributes
toCommonProperties properties =
    { stroke = CC.colorToHex properties.strokeColor
    , strokeWidth = toString properties.strokeWidth
    , fill = CC.colorToHex properties.fillColor
    }
